version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quantum_keygen_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./saved_models:/app/saved_models
    restart: unless-stopped
